"""Initial migration: create all tables

Revision ID: a5fc4bc98b84
Revises: 
Create Date: 2025-11-20 18:20:00.659632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5fc4bc98b84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('enrollment_start', sa.Date(), nullable=False),
    sa.Column('enrollment_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_academic_periods_code'), 'academic_periods', ['code'], unique=True, schema='source')
    op.create_index(op.f('ix_source_academic_periods_id'), 'academic_periods', ['id'], unique=False, schema='source')
    op.create_table('academic_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_value', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_academic_rules_id'), 'academic_rules', ['id'], unique=False, schema='source')
    op.create_index(op.f('ix_source_academic_rules_rule_type'), 'academic_rules', ['rule_type'], unique=False, schema='source')
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_classrooms_code'), 'classrooms', ['code'], unique=True, schema='source')
    op.create_index(op.f('ix_source_classrooms_id'), 'classrooms', ['id'], unique=False, schema='source')
    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_professors_code'), 'professors', ['code'], unique=True, schema='source')
    op.create_index(op.f('ix_source_professors_email'), 'professors', ['email'], unique=True, schema='source')
    op.create_index(op.f('ix_source_professors_id'), 'professors', ['id'], unique=False, schema='source')
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('faculty', sa.String(length=100), nullable=False),
    sa.Column('credits_required', sa.Integer(), nullable=False),
    sa.Column('duration_semesters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_programs_code'), 'programs', ['code'], unique=True, schema='source')
    op.create_index(op.f('ix_source_programs_id'), 'programs', ['id'], unique=False, schema='source')
    op.create_table('enrollment_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_period_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_period_id'], ['source.academic_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sghu'
    )
    op.create_index(op.f('ix_sghu_enrollment_periods_academic_period_id'), 'enrollment_periods', ['academic_period_id'], unique=False, schema='sghu')
    op.create_index(op.f('ix_sghu_enrollment_periods_id'), 'enrollment_periods', ['id'], unique=False, schema='sghu')
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('current_semester', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['source.programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_students_code'), 'students', ['code'], unique=True, schema='source')
    op.create_index(op.f('ix_source_students_email'), 'students', ['email'], unique=True, schema='source')
    op.create_index(op.f('ix_source_students_id'), 'students', ['id'], unique=False, schema='source')
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('theory_hours', sa.Integer(), nullable=True),
    sa.Column('practice_hours', sa.Integer(), nullable=True),
    sa.Column('lab_hours', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['source.programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_subjects_code'), 'subjects', ['code'], unique=True, schema='source')
    op.create_index(op.f('ix_source_subjects_id'), 'subjects', ['id'], unique=False, schema='source')
    op.create_table('student_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_period_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_period_id'], ['sghu.enrollment_periods.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['source.students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sghu'
    )
    op.create_index(op.f('ix_sghu_student_enrollments_enrollment_period_id'), 'student_enrollments', ['enrollment_period_id'], unique=False, schema='sghu')
    op.create_index(op.f('ix_sghu_student_enrollments_id'), 'student_enrollments', ['id'], unique=False, schema='sghu')
    op.create_index(op.f('ix_sghu_student_enrollments_student_id'), 'student_enrollments', ['student_id'], unique=False, schema='sghu')
    op.create_table('academic_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credits_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['source.students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['source.subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_academic_history_id'), 'academic_history', ['id'], unique=False, schema='source')
    op.create_index(op.f('ix_source_academic_history_student_id'), 'academic_history', ['student_id'], unique=False, schema='source')
    op.create_index(op.f('ix_source_academic_history_subject_id'), 'academic_history', ['subject_id'], unique=False, schema='source')
    op.create_table('course_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('enrolled_count', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['source.classrooms.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['source.academic_periods.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['source.professors.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['source.subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_course_sections_id'), 'course_sections', ['id'], unique=False, schema='source')
    op.create_table('financial_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('has_debt', sa.String(length=10), nullable=False),
    sa.Column('debt_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['source.students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_financial_status_id'), 'financial_status', ['id'], unique=False, schema='source')
    op.create_index(op.f('ix_source_financial_status_student_id'), 'financial_status', ['student_id'], unique=True, schema='source')
    op.create_table('prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_subject_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_subject_id'], ['source.subjects.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['source.subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_prerequisites_id'), 'prerequisites', ['id'], unique=False, schema='source')
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['source.programs.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['source.subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_study_plans_id'), 'study_plans', ['id'], unique=False, schema='source')
    op.create_table('enrollment_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['sghu.student_enrollments.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['source.course_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sghu'
    )
    op.create_index(op.f('ix_sghu_enrollment_subjects_enrollment_id'), 'enrollment_subjects', ['enrollment_id'], unique=False, schema='sghu')
    op.create_index(op.f('ix_sghu_enrollment_subjects_id'), 'enrollment_subjects', ['id'], unique=False, schema='sghu')
    op.create_index(op.f('ix_sghu_enrollment_subjects_section_id'), 'enrollment_subjects', ['section_id'], unique=False, schema='sghu')
    op.create_table('generated_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('generation_method', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['sghu.student_enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sghu'
    )
    op.create_index(op.f('ix_sghu_generated_schedules_enrollment_id'), 'generated_schedules', ['enrollment_id'], unique=False, schema='sghu')
    op.create_index(op.f('ix_sghu_generated_schedules_id'), 'generated_schedules', ['id'], unique=False, schema='sghu')
    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('process_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['sghu.student_enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sghu'
    )
    op.create_index(op.f('ix_sghu_processing_logs_enrollment_id'), 'processing_logs', ['enrollment_id'], unique=False, schema='sghu')
    op.create_index(op.f('ix_sghu_processing_logs_id'), 'processing_logs', ['id'], unique=False, schema='sghu')
    op.create_table('moodle_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('moodle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['source.course_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_moodle_courses_course_code'), 'moodle_courses', ['course_code'], unique=False, schema='source')
    op.create_index(op.f('ix_source_moodle_courses_id'), 'moodle_courses', ['id'], unique=False, schema='source')
    op.create_index(op.f('ix_source_moodle_courses_moodle_id'), 'moodle_courses', ['moodle_id'], unique=True, schema='source')
    op.create_table('section_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['source.course_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_section_schedules_id'), 'section_schedules', ['id'], unique=False, schema='source')
    op.create_table('schedule_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['sghu.generated_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sghu'
    )
    op.create_index(op.f('ix_sghu_schedule_conflicts_id'), 'schedule_conflicts', ['id'], unique=False, schema='sghu')
    op.create_index(op.f('ix_sghu_schedule_conflicts_schedule_id'), 'schedule_conflicts', ['schedule_id'], unique=False, schema='sghu')
    op.create_table('schedule_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['sghu.generated_schedules.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['source.course_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sghu'
    )
    op.create_index(op.f('ix_sghu_schedule_slots_id'), 'schedule_slots', ['id'], unique=False, schema='sghu')
    op.create_index(op.f('ix_sghu_schedule_slots_schedule_id'), 'schedule_slots', ['schedule_id'], unique=False, schema='sghu')
    op.create_index(op.f('ix_sghu_schedule_slots_section_id'), 'schedule_slots', ['section_id'], unique=False, schema='sghu')
    op.create_table('moodle_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moodle_course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['moodle_course_id'], ['source.moodle_courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['source.students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='source'
    )
    op.create_index(op.f('ix_source_moodle_enrollments_id'), 'moodle_enrollments', ['id'], unique=False, schema='source')
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index(op.f('ix_source_moodle_enrollments_id'), table_name='moodle_enrollments', schema='source')
    op.drop_table('moodle_enrollments', schema='source')
    op.drop_index(op.f('ix_sghu_schedule_slots_section_id'), table_name='schedule_slots', schema='sghu')
    op.drop_index(op.f('ix_sghu_schedule_slots_schedule_id'), table_name='schedule_slots', schema='sghu')
    op.drop_index(op.f('ix_sghu_schedule_slots_id'), table_name='schedule_slots', schema='sghu')
    op.drop_table('schedule_slots', schema='sghu')
    op.drop_index(op.f('ix_sghu_schedule_conflicts_schedule_id'), table_name='schedule_conflicts', schema='sghu')
    op.drop_index(op.f('ix_sghu_schedule_conflicts_id'), table_name='schedule_conflicts', schema='sghu')
    op.drop_table('schedule_conflicts', schema='sghu')
    op.drop_index(op.f('ix_source_section_schedules_id'), table_name='section_schedules', schema='source')
    op.drop_table('section_schedules', schema='source')
    op.drop_index(op.f('ix_source_moodle_courses_moodle_id'), table_name='moodle_courses', schema='source')
    op.drop_index(op.f('ix_source_moodle_courses_id'), table_name='moodle_courses', schema='source')
    op.drop_index(op.f('ix_source_moodle_courses_course_code'), table_name='moodle_courses', schema='source')
    op.drop_table('moodle_courses', schema='source')
    op.drop_index(op.f('ix_sghu_processing_logs_id'), table_name='processing_logs', schema='sghu')
    op.drop_index(op.f('ix_sghu_processing_logs_enrollment_id'), table_name='processing_logs', schema='sghu')
    op.drop_table('processing_logs', schema='sghu')
    op.drop_index(op.f('ix_sghu_generated_schedules_id'), table_name='generated_schedules', schema='sghu')
    op.drop_index(op.f('ix_sghu_generated_schedules_enrollment_id'), table_name='generated_schedules', schema='sghu')
    op.drop_table('generated_schedules', schema='sghu')
    op.drop_index(op.f('ix_sghu_enrollment_subjects_section_id'), table_name='enrollment_subjects', schema='sghu')
    op.drop_index(op.f('ix_sghu_enrollment_subjects_id'), table_name='enrollment_subjects', schema='sghu')
    op.drop_index(op.f('ix_sghu_enrollment_subjects_enrollment_id'), table_name='enrollment_subjects', schema='sghu')
    op.drop_table('enrollment_subjects', schema='sghu')
    op.drop_index(op.f('ix_source_study_plans_id'), table_name='study_plans', schema='source')
    op.drop_table('study_plans', schema='source')
    op.drop_index(op.f('ix_source_prerequisites_id'), table_name='prerequisites', schema='source')
    op.drop_table('prerequisites', schema='source')
    op.drop_index(op.f('ix_source_financial_status_student_id'), table_name='financial_status', schema='source')
    op.drop_index(op.f('ix_source_financial_status_id'), table_name='financial_status', schema='source')
    op.drop_table('financial_status', schema='source')
    op.drop_index(op.f('ix_source_course_sections_id'), table_name='course_sections', schema='source')
    op.drop_table('course_sections', schema='source')
    op.drop_index(op.f('ix_source_academic_history_subject_id'), table_name='academic_history', schema='source')
    op.drop_index(op.f('ix_source_academic_history_student_id'), table_name='academic_history', schema='source')
    op.drop_index(op.f('ix_source_academic_history_id'), table_name='academic_history', schema='source')
    op.drop_table('academic_history', schema='source')
    op.drop_index(op.f('ix_sghu_student_enrollments_student_id'), table_name='student_enrollments', schema='sghu')
    op.drop_index(op.f('ix_sghu_student_enrollments_id'), table_name='student_enrollments', schema='sghu')
    op.drop_index(op.f('ix_sghu_student_enrollments_enrollment_period_id'), table_name='student_enrollments', schema='sghu')
    op.drop_table('student_enrollments', schema='sghu')
    op.drop_index(op.f('ix_source_subjects_id'), table_name='subjects', schema='source')
    op.drop_index(op.f('ix_source_subjects_code'), table_name='subjects', schema='source')
    op.drop_table('subjects', schema='source')
    op.drop_index(op.f('ix_source_students_id'), table_name='students', schema='source')
    op.drop_index(op.f('ix_source_students_email'), table_name='students', schema='source')
    op.drop_index(op.f('ix_source_students_code'), table_name='students', schema='source')
    op.drop_table('students', schema='source')
    op.drop_index(op.f('ix_sghu_enrollment_periods_id'), table_name='enrollment_periods', schema='sghu')
    op.drop_index(op.f('ix_sghu_enrollment_periods_academic_period_id'), table_name='enrollment_periods', schema='sghu')
    op.drop_table('enrollment_periods', schema='sghu')
    op.drop_index(op.f('ix_source_programs_id'), table_name='programs', schema='source')
    op.drop_index(op.f('ix_source_programs_code'), table_name='programs', schema='source')
    op.drop_table('programs', schema='source')
    op.drop_index(op.f('ix_source_professors_id'), table_name='professors', schema='source')
    op.drop_index(op.f('ix_source_professors_email'), table_name='professors', schema='source')
    op.drop_index(op.f('ix_source_professors_code'), table_name='professors', schema='source')
    op.drop_table('professors', schema='source')
    op.drop_index(op.f('ix_source_classrooms_id'), table_name='classrooms', schema='source')
    op.drop_index(op.f('ix_source_classrooms_code'), table_name='classrooms', schema='source')
    op.drop_table('classrooms', schema='source')
    op.drop_index(op.f('ix_source_academic_rules_rule_type'), table_name='academic_rules', schema='source')
    op.drop_index(op.f('ix_source_academic_rules_id'), table_name='academic_rules', schema='source')
    op.drop_table('academic_rules', schema='source')
    op.drop_index(op.f('ix_source_academic_periods_id'), table_name='academic_periods', schema='source')
    op.drop_index(op.f('ix_source_academic_periods_code'), table_name='academic_periods', schema='source')
    op.drop_table('academic_periods', schema='source')
    # ### end Alembic commands ###
